### PR TITLE
rewrite

### PR DESCRIPTION
**Pull request by RemainingToast**

### CODE REVIEW

**Comment by RemainingToast** [comment]
basically just need a GUI then client is back to having the features that it used to, plus some. (and rewrites)

**Comment by Vonr** [comment]
yooo what toast client undied?

**Comment by RemainingToast** [comment]
> yooo what toast client undied?

🤓

**Comment by RemainingToast** [comment]
Client Base stuff to work on next:

- Notifications
- Hud Editor/Hud Components
- ClickGUI Config

**Pull request merged**
